name: bq_dbt_exam_practise

profile: bq_dbt_exam_practise

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  bq_dbt_exam_practise:
    +schema: raw

models:
  bq_dbt_exam_practise:
    +static_analysis: strict
    # Materialize staging models as views, and marts as tables
    staging:
      +materialized: view
    marts:
      +materialized: table
