name: bq_dbt_exam_practise

profile: bq_dbt_exam_practise

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

models:
  bq_dbt_exam_practise:
    staging:
      +schema: "{{ 'staging_dev' if target.name == 'dev' else 'staging' }}"
      +materialized: view
    intermediate:
      +schema: "{{ 'int_dev' if target.name == 'dev' else 'int'}}"
      +materialized: view
    marts:
      +materialized: table
      +schema: "{{ 'mart_dev' if target.name == 'dev' else 'mart'}}"

snapshots:
  bq_dbt_exam_practise:
    +target_schema: "{{ 'snap_dev' if target.name == 'dev' else 'snap' }}"
    +strategy: check
    +invalidate_hard_deletes: true